name: CI
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    services:
      flask-app:
        image: python:3.9
        options: >-
          --health-cmd "curl -f http://localhost:5000/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3.9 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start Flask application
      run: |
        python3.9 -m app.app &

    - name: Check Flask application health
      run: |
          python3.9 -c "
          import os
          from app.app import app
          client = app.test_client()
          response = client.get('/health')
          assert response.status_code == 200
          assert response.json['status'] == 'OK'
          "
    - name: Run unit tests
      run: |
        python3.9 -m unittest discover -s . -p "test_*.py"
    - name: Create build directory
      run: |
        mkdir -p build
        - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: build/