name: Credit Card Validator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set hostname
      run: |
        echo "127.0.0.1 ValidateCard.local" | sudo tee -a /etc/hosts

    - name: Build and run Docker Compose
      run: |
        docker-compose up -d --build

    - name: Check application health
      run: |
        sleep 5
        curl --fail http://ValidateCard.local:5000/api/validate/1234567890123456

    - name: Open application URL
      run: |
        open http://ValidateCard.local:5000/api/validate/1234567890123456
      if: success()